HathorNetwork/hathor-explorer-service

- .github/workflows/deploy.yml
- Makefile
- serverless.yml
This PR adds a workflow on Github Actions to automate the deployment of the service in our backend.
Both our serverless functions and docker containers are deployed.
For serverless, we just use its own deploy command `serverless deploy` with the right configuration.
For the docker containers, we just push a new image to our repository. Check this to learn more about what happens after the image is pushed until deployment is complete: https://github.com/HathorNetwork/ops-tools/issues/20#issuecomment-858750894
> Ci: Create deployment pipeline

- .github/workflows/deploy.yml
What's included:
- https://github.com/HathorNetwork/hathor-explorer-service/pull/27
> PR Release

- .github/workflows/deploy.yml
Another error in our deploy pipeline, this time preventing the deploys from running.
> fix: wrong variable used in deploy pipeline

- .github/workflows/deploy.yml
- common/configuration.py
- serverless.yml
- tests/unit/utils/wrappers/aws/test_api_gateway.py
- utils/wrappers/aws/api_gateway.py
https://github.com/HathorNetwork/hathor-explorer-service/issues/23
> feat: add cors configuration by env vars

- .github/workflows/pr-validation.yml
We should have tests running in all PRs
Added a new Github Actions pipeline to run tests in all PRs
> ci: add pr-validation pipeline

- common/errors.py
- gateways/clients/responses/hathor_core/hathor_core_token_response.py
- gateways/metadata_gateway.py
- gateways/node_gateway.py
- gateways/token_gateway.py
- handlers/get_dag_metadata_handler.py
- handlers/get_node_handler.py
- handlers/get_token_handler.py
- tests/unit/gateways/clients/responses/hathor_core/test_hathor_core_token_response.py
- tests/unit/gateways/test_metadata_gateway.py
- tests/unit/utils/wrappers/aws/test_api_gateway.py
- utils/wrappers/aws/api_gateway.py
Resolves @msbrogli review on #67
> refactor: custom errors

- domain/network/network.py
- gateways/clients/cache_client.py
- gateways/node_gateway.py
- handlers/get_network_handler.py
- handlers/node_data_aggregator.py
- poetry.lock
- pyproject.toml
- serverless.yml
- tests/fixtures/network_factory.py
- tests/unit/domain/network/test_network.py
- tests/unit/domain/network/test_node.py
- tests/unit/gateways/test_node_gateway.py
- tests/unit/usecases/test_aggregate_node_data.py
- tests/unit/usecases/test_get_network.py
- tests/unit/utils/wrappers/aws/test_api_gateway.py
- text/0002-data-aggregator.md
- usecases/aggregate_node_data.py
- usecases/collect_nodes_statuses.py
- usecases/get_network.py
- network data is always updated when node and peer data changes
- network endpoint
> feat: Network data aggregator

- poetry.lock
- pyproject.toml
Remove this dependency because it caused issues on the lambda environment
> fix: remove asyncio from deps

- package-lock.json
- package.json
- pyproject.toml
> Bump version to v0.1.14

- .github/workflows/deploy.yml
- Makefile
- package-lock.json
- package.json
- serverless.yml
- We should have alarms for errors in the Lambdas deployed by Serverless
- Minor alarm if 2 errors happen in 60 seconds
- Major alarm if 10 errors happen in 5 consecutive periods of 60 seconds
> chore: create alarms for errors in Lambdas

- package-lock.json
- package.json
- pyproject.toml
- https://github.com/HathorNetwork/hathor-explorer-service/pull/128
- https://github.com/HathorNetwork/hathor-explorer-service/pull/129
- https://github.com/HathorNetwork/hathor-explorer-service/pull/122
> bump: v0.2.0

- .github/workflows/deploy.yml
Serverless must be able to get ES info from env variables.
> Change deploy file to include ElasticSearch variables

- gateways/clients/wallet_service_db_client.py
- tests/unit/gateways/clients/test_wallet_service_db_client.py
- Include HTR on the first page of the address tokens API if it exists on the address history
> feat: always include htr

- .github/workflows/deploy.yml
Allow configuring both testnet and mainnet deploys on github
> fix: deploy config for new envs

- package-lock.json
- package.json
- pyproject.toml
> chore: bump v0.5.0

- package-lock.json
- package.json
- pyproject.toml
> chore: bump v0.6.0

- gateways/clients/wallet_service_db_client.py
- gateways/token_api_gateway.py
- gateways/token_balances_api_gateway.py
- gateways/wallet_service_gateway.py
- handlers/token_api.py
- package-lock.json
- package.json
- pyproject.toml
- serverless.yml
- tests/unit/gateways/clients/test_elastic_search_client.py
- tests/unit/gateways/clients/test_wallet_service_db_client.py
- tests/unit/gateways/test_token_api_gateway.py
- tests/unit/gateways/test_token_balances_api_gateway.py
- tests/unit/gateways/test_wallet_service.py
- tests/unit/usecases/test_token_api.py
- tests/unit/utils/elastic_search/test_elastic_search_utils.py
- usecases/token_api.py
- utils/elastic_search/elastic_search_utils.py
- utils/elastic_search/transformations/token_api.py
> Release v0.6.0

- package-lock.json
- package.json
- pyproject.toml
> chore: bump v0.6.1

- gateways/token_api_gateway.py
- package-lock.json
- package.json
- pyproject.toml
> Release v0.6.1

- gateways/clients/wallet_service_db_client.py
- Order address tokens by latest tx `timestamp` instead of `updated_at` column
> feat: order address tokens by latest tx timestamp

- gateways/clients/wallet_service_db_client.py
- package-lock.json
- package.json
- pyproject.toml
> Release version v0.6.2

- gateways/clients/wallet_service_db_client.py
- gateways/wallet_service_gateway.py
- handlers/wallet_service.py
- tests/unit/gateways/clients/test_wallet_service_db_client.py
- tests/unit/gateways/test_wallet_service.py
- tests/unit/usecases/test_wallet_service.py
- usecases/wallet_service.py
This PR is part of the https://github.com/HathorNetwork/internal-issues/issues/131 design
- We should paginate using the last tx timestamp and tx_id from last page
> refactor: improve pagination

- package-lock.json
- package.json
- pyproject.toml
> chore: bump v0.7.1

- package-lock.json
- package.json
- pyproject.toml
- serverless.yml
> Release v0.7.1

- package-lock.json
- package.json
- pyproject.toml
> chore: bump version v0.7.2

- Dockerfile_Daemons
- package-lock.json
- package.json
- pyproject.toml
> Release v0.7.2

- .github/workflows/deploy.yml
- We should automatically deploy the dev environment when commits are made to the `dev` branch.
> ci: deploy dev environment

- Makefile
- daemons/data_collector.py
- gateways/node_gateway.py
- usecases/collect_nodes_statuses.py
- We should log some events in the DataCollector daemon so we know it's still working just by looking at the logs.
> chore: improve logging

- package-lock.json
- package.json
- pyproject.toml
- https://github.com/HathorNetwork/hathor-explorer-service/pull/218
- https://github.com/HathorNetwork/hathor-explorer-service/pull/217
> bump: v0.7.3

- .github/workflows/deploy.yml
- .github/workflows/pr-validation.yml
- Makefile
- daemons/data_collector.py
- gateways/node_gateway.py
- package-lock.json
- package.json
- pyproject.toml
- usecases/collect_nodes_statuses.py
- https://github.com/HathorNetwork/hathor-explorer-service/pull/218
- https://github.com/HathorNetwork/hathor-explorer-service/pull/217
- https://github.com/HathorNetwork/hathor-explorer-service/pull/221
> release: v0.7.3

- .github/workflows/codeql.yml
- tests/fixtures/node_factory.py
- tests/unit/gateways/clients/test_wallet_service_db_client.py
- tests/unit/gateways/test_node_gateway.py
- tests/unit/gateways/test_token_api_gateway.py
- tests/unit/usecases/test_block_api.py
- usecases/aggregate_node_data.py
This is the same as https://github.com/HathorNetwork/hathor-explorer-service/pull/222, but including the fixes for the errors reported there.
In this PR there shouldn't be any errors reported.
The fixed errors:
- https://github.com/HathorNetwork/hathor-explorer-service/security/code-scanning/9
- https://github.com/HathorNetwork/hathor-explorer-service/security/code-scanning/3
- https://github.com/HathorNetwork/hathor-explorer-service/security/code-scanning/4
- https://github.com/HathorNetwork/hathor-explorer-service/security/code-scanning/5
- https://github.com/HathorNetwork/hathor-explorer-service/security/code-scanning/6
- https://github.com/HathorNetwork/hathor-explorer-service/security/code-scanning/7
- https://github.com/HathorNetwork/hathor-explorer-service/security/code-scanning/8
> ci: Add CodeQL workflow

- package-lock.json
- package.json
- pyproject.toml
- https://github.com/HathorNetwork/hathor-explorer-service/pull/225
- https://github.com/HathorNetwork/hathor-explorer-service/pull/224
> bump: v0.7.4

- .github/workflows/codeql.yml
- package-lock.json
- package.json
- poetry.lock
- pyproject.toml
- serverless.yml
- tests/fixtures/node_factory.py
- tests/unit/gateways/clients/test_wallet_service_db_client.py
- tests/unit/gateways/test_node_gateway.py
- tests/unit/gateways/test_token_api_gateway.py
- tests/unit/usecases/test_block_api.py
- usecases/aggregate_node_data.py
- https://github.com/HathorNetwork/hathor-explorer-service/pull/225
- https://github.com/HathorNetwork/hathor-explorer-service/pull/224
> Release: v0.7.4

- package-lock.json
- package.json
- poetry.lock
- pyproject.toml
- https://github.com/HathorNetwork/hathor-explorer-service/pull/230
> Release: v0.7.5

- serverless.yml
- We should add tags to resources created by Serverless
> chore: add tags on serverless resources

- package-lock.json
- package.json
- pyproject.toml
- serverless.yml
- https://github.com/HathorNetwork/hathor-explorer-service/pull/240
> Release: v0.7.6

- .github/workflows/deploy.yml
- Include here all things that this PR should solve
> chore: use aem fullnode

- package-lock.json
- package.json
- pyproject.toml
> bump: v0.7.7

- gateways/clients/hathor_core_client.py
- gateways/node_api_gateway.py
- handlers/node_api.py
- serverless.yml
- tests/unit/gateways/test_node_api_gateway.py
- tests/unit/usecases/test_token_balances_api.py
> feat: change push_tx to post

- gateways/clients/hathor_core_client.py
- gateways/node_api_gateway.py
- handlers/node_api.py
- serverless.yml
- tests/unit/gateways/test_node_api_gateway.py
- tests/unit/usecases/test_node_api.py
- usecases/node_api.py
- Implement new `GET /feature` endpoint
> feat(feature-activation): add feature endpoint

- package-lock.json
- package.json
- pyproject.toml
> chore: bump version v0.8.0

- .github/workflows/deploy.yml
- serverless.yml
- Disable cache for push tx api
> chore: disable cache for push tx

- package-lock.json
- package.json
- pyproject.toml
- https://github.com/HathorNetwork/hathor-explorer-service/pull/265
> bump: v0.8.1

- package-lock.json
- package.json
- pyproject.toml
- serverless.yml
- https://github.com/HathorNetwork/hathor-explorer-service/pull/265
> Release: v0.8.1

- .env.example
- .github/workflows/deploy.yml
- Makefile
- gateways/clients/responses/hathor_core/hathor_core_token_response.py
- gateways/network_statistics_api_gateway.py
- handlers/dag_metadata_handler.py
- handlers/get_network_handler.py
- handlers/get_node_handler.py
- handlers/get_token_handler.py
- handlers/list_nodes_handler.py
- handlers/network_statistics.py
- handlers/node_data_aggregator.py
- handlers/wallet_service.py
- serverless.yml
- tests/load/README.md
- tests/load/network_statistics_smoke_test.js
- usecases/network_statistics_api.py
- Implement the `/network-statistics` endpoint
- Uses elasticsearch to query transaction basic statistics such number of transactions, number of blocks and heighest height
> feat: network-statistics api

- package-lock.json
- package.json
- pyproject.toml
> bump: explorer-service to v0.8.2

- .env.example
- .github/workflows/deploy.yml
- Makefile
- gateways/clients/responses/hathor_core/hathor_core_token_response.py
- gateways/network_statistics_api_gateway.py
- handlers/dag_metadata_handler.py
- handlers/get_network_handler.py
- handlers/get_node_handler.py
- handlers/get_token_handler.py
- handlers/list_nodes_handler.py
- handlers/network_statistics.py
- handlers/node_data_aggregator.py
- handlers/wallet_service.py
- package-lock.json
- package.json
- pyproject.toml
- serverless.yml
- tests/load/README.md
- tests/load/network_statistics_smoke_test.js
- usecases/network_statistics_api.py
> Release: v0.8.2

- .github/workflows/deploy.yml
- Add CORS configuration for proteina stating environment of the site on our dev-testnet environment
> chore:  allows proteina staging URLs on CORS rules for testnet and mainnet environments

- package-lock.json
- package.json
- pyproject.toml
- https://github.com/HathorNetwork/hathor-explorer-service/pull/280
- https://github.com/HathorNetwork/hathor-explorer-service/pull/276
> bump: v0.9.0

- gateways/clients/elastic_search_client.py
- gateways/network_statistics_api_gateway.py
- tests/unit/gateways/test_network_statistics_api_gateway.py
- tests/unit/usecases/test_network_statistics_api.py
- Add some unit tests for the network statistics API logic added in https://github.com/HathorNetwork/hathor-explorer-service/pull/268
We've been getting errors in the coverage check because we've dropped below 90%.
> ci: tests for network statistics api

- package-lock.json
- package.json
- pyproject.toml
- https://github.com/HathorNetwork/hathor-explorer-service/pull/279
- https://github.com/HathorNetwork/hathor-explorer-service/pull/285
> bump: v0.10.0

- package-lock.json
- package.json
- pyproject.toml
- https://github.com/HathorNetwork/hathor-explorer-service/pull/290
- https://github.com/HathorNetwork/hathor-explorer-service/pull/292
> bump: v0.11.0

- package-lock.json
- package.json
- pyproject.toml
- https://github.com/HathorNetwork/hathor-explorer-service/pull/296
- https://github.com/HathorNetwork/hathor-explorer-service/pull/295
> bump: v0.11.1

- daemons_runner.py
- domain/network/node.py
- package-lock.json
- package.json
- pyproject.toml
- https://github.com/HathorNetwork/hathor-explorer-service/pull/296
- https://github.com/HathorNetwork/hathor-explorer-service/pull/295
> Release: v0.11.1

- package-lock.json
- package.json
- pyproject.toml
- Bump to version 0.12.0
It adds:
- #299
- #301
> bump: v0.12.0

- .github/workflows/deploy.yml
- domain/network/network.py
- domain/network/node.py
- package-lock.json
- package.json
- pyproject.toml
- tests/fixtures/network_factory.py
- tests/fixtures/node_factory.py
- feat: support dag.best_block from node status
- chore: remove proteina's URLs from CORS rules (#301)
- bump: v0.12.0 (#302)
> release: v0.12.0

- package-lock.json
- package.json
- pyproject.toml
- Bump version to 0.12.1
Patch:
- #304
> bump: v0.12.1

- domain/network/network.py
- package-lock.json
- package.json
- pyproject.toml
- tests/unit/gateways/test_node_gateway.py
- bump: v0.12.1 (#305)
- fix: legacy node data without best_block property (#304)
> release: v0.12.1

- .github/workflows/pr-validation.yml
- Dockerfile_Serverless
- package-lock.json
- package.json
- poetry.lock
- pyproject.toml
- serverless.yml
- https://github.com/HathorNetwork/hathor-explorer-service/pull/308
> Release: v0.13.0

- package-lock.json
- package.json
- pyproject.toml
- https://github.com/HathorNetwork/hathor-explorer-service/pull/314
- https://github.com/HathorNetwork/hathor-explorer-service/pull/315
> bump: v0.15.0

- package-lock.json
- package.json
- pyproject.toml
- serverless.yml
- https://github.com/HathorNetwork/hathor-explorer-service/pull/314
- https://github.com/HathorNetwork/hathor-explorer-service/pull/315
> Release: v0.15.0

- package-lock.json
- package.json
- pyproject.toml
> chore: bump package to v0.16.0

- package-lock.json
- package.json
- pyproject.toml
> chore: bump package to v0.16.1

- package-lock.json
- package.json
- pyproject.toml
- serverless.yml
> Release v0.16.1

- package-lock.json
- package.json
- pyproject.toml
> bump: v0.17.0

- package-lock.json
- package.json
- pyproject.toml
> chore: bump package to v0.18.0

- .github/workflows/deploy.yml
- CORS regex should accept dashes
> fix: CORS regex should accept dashes

- package-lock.json
- package.json
- pyproject.toml
- https://github.com/HathorNetwork/hathor-explorer-service/pull/337
> bump: v0.18.1

- .github/workflows/deploy.yml
- package-lock.json
- package.json
- pyproject.toml
- https://github.com/HathorNetwork/hathor-explorer-service/pull/337
> Release: v0.18.1

- .github/workflows/deploy-reusable.yml
- .github/workflows/deploy.yml
- The APIs in the hathor play full node are up to date with the latest changes on the nano hathor core
- Update version of upload/download artifact to v4
> chore: use hathorplay node to deploy nano testnet explorer service

- .github/workflows/deploy.yml
- We should have a dev environment for nano-testnet, basically using the same backend as the main one, but without CORS.
> chore: deploy nano-testnet-dev environment

- package-lock.json
- package.json
- pyproject.toml
> chore: bump package to v0.19.0

- .github/workflows/deploy.yml
- serverless.yml
- Make sure we can deploy to the new nano-testnet bravo network
> chore: nano-testnet bravo

- .env.example
- .github/workflows/deploy.yml
- Makefile
- Allow deploys to the new testnet-hotel
> chore: testnet-hotel

- .github/workflows/deploy.yml
- The Testnet-golf should use its specific domains for fullnodes
> fix: Testnet Golf config
