.github/workflows/deploy.yml
Changes:
- We had a Github Actions syntax wrong for if conditionals. This is the right syntax: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#example-expression-in-an-if-conditional
=> fix: syntax error in deploy pipeline

.github/workflows/deploy.yml, common/configuration.py, gateways/clients/cache_client.py, gateways/clients/responses/hathor_core/hathor_core_status_response.py, gateways/node_gateway.py, serverless.yml, tests/unit/gateways/test_node_gateway.py, usecases/save_node_data.py
=> fix: clear obsolete node cache data

common/configuration.py, common/logging.py, poetry.lock, pyproject.toml
Creates a uniform logging solution that enabled json logging (to use with cloudwatch).
Exception logs should include the traceback inside the json so the cloudwatch logs are not affected.
(Tracebacks usually are multiple lines which cloudwatch interprets as multiple logs)
=> chore: structured logging

gateways/clients/hathor_core_client.py, gateways/node_api_gateway.py, handlers/node_api.py, serverless.yml, tests/fixtures/node_api_factory.py, tests/unit/common/test_configuration.py, tests/unit/gateways/test_metadata_gateway.py, tests/unit/gateways/test_node_api_gateway.py, tests/unit/usecases/test_node_api.py, usecases/node_api.py, utils/wrappers/aws/api_gateway.py
- Implements the api described on the design #83
- Does not alter parameters passed to the full-node and returns the exact response from the full-node
=> feat: node api proxy

serverless.yml
The default cache time for any handler is 5 minutes unless explicitly defined.
The cache time for the metadata api being 5 minutes makes changes take longer to be in effect and with minimal benefits.
The decision to change to 10s makes peak activity manageable and changes are noticed faster.
Change cache time for metadata api to 10s.
=> chore: cache time revision

package-lock.json, package.json, pyproject.toml, serverless.yml
During testnet deploy this error occured:
```
Value 'hathor-explorer-service-testnet-node_api_get_transaction_acc_weight' at 'functionName' failed to satisfy constraint: Member must have length less than or equal to 64
```
The `hathor-explorer-service-testnet-` prefix (length 32) for testnet and `hathor-explorer-service-mainnet-` (length 32) for mainnet are added to identify the service and network of the lembda, but this leaves 32 characters for the name which `node_api_get_transaction_acc_weight` (length 35) does not fit.
- Change `node_api_get_transaction_acc_weight` to a name of 32 characters or less.
=> fix: lambda name > 64 char

gateways/node_api_gateway.py, handlers/node_api.py, serverless.yml, tests/unit/gateways/test_node_api_gateway.py, tests/unit/usecases/test_node_api.py, usecases/node_api.py
Since [this PR](https://github.com/HathorNetwork/hathor-explorer/pull/154) was merged, tokens API is not being used anymore, so we are removing it. A new token API will be designed as part of [this issue](https://github.com/HathorNetwork/hathor-explorer-service/issues/73).
It solves issue #111
Hathor Explorer must continue to work without any UI modification, especially when listing tokens in a transaction or showing token info. This video demonstrates this (This test was performed on my local environment pointing to testnet):
https://user-images.githubusercontent.com/3287486/152403428-84f58790-febf-4ac2-b3ac-f259a577d373.mov
=> feat: remove unused tokens API

serverless.yml
We should not alert in case of missing data in the CloudWatch alarms created for the Lambdas.
This behavior was observed in other projects with similar alarms, and this will avoid the same thing from happening here.
Reference:
https://www.serverless.com/plugins/serverless-plugin-aws-alerts
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/AlarmThatSendsEmail.html#alarms-and-missing-data
=> fix: avoid alerting on missing data

README.md, serverless.yml
If the user access ```https://explorer.hathor.network```, it will work normally. However, if after that the user tries to access ```https://explorer.mainnet.hathor.network``` he/she will see a CORS problem. This happens because the first request is cached and returned on the second request. The browser identifies that the ```Origin``` in the request is different than the ```Access-Control-Allow-Origin``` in the response and shows the CORS error message to the user.
To solve that, the ```Origin``` was introduced as a cache key on ```node_api_get_version``` endpoint, which is the API that is returning CORS error.
Tests were performed using Postman and deploying a local stack of Explorer Service on AWS. Now, when the origin changes (And matches the Regex), the …
=> Fix CORS problem due to API GW caching

Makefile, docker-compose.yml, poetry.lock, pyproject.toml, serverless.yml, tests/unit/usecases/test_aggregate_node_data.py, usecases/aggregate_node_data.py
On the data aggregator lambda, the [deepdiff](https://github.com/seperman/deepdiff) lib is used to check if there is any difference between the network data that was aggregated and the one saved on cache. If there is a difference we save the most recent one.
The network data is aggregated from node statuses of the nodes, and some reach over 32Kb of data (after filtering unnecessary data, before filtering it would be over 1Mb) this makes the deepdiff take more time to find all differences on every request.
The proposed solution is to stop the deepdiff when it finds the first difference.
=> chore: stop diff early

serverless.yml
- We should have logs for API Gateway
I observed a high number of 4xx requests in the API Gateway monitoring, but couldn't find the reason.
- Creating a role for API Gateway logging: https://aws.amazon.com/premiumsupport/knowledge-center/api-gateway-cloudwatch-logs/
- Serverless reference: https://www.serverless.com/framework/docs/providers/aws/events/apigateway#logs
=> chore: enable API Gateway logs

package.json, serverless.yml
Throttle tokens API to prevent resource exhaustion
The throttle values were created based on the traffic that was observed on Transactions API.
=> feat: add throttling to tokens api

tests/unit/gateways/clients/test_elastic_search_client.py, tests/unit/gateways/test_token_api_gateway.py, tests/unit/usecases/test_token_api.py, tests/unit/utils/elastic_search/test_elastic_search_utils.py, utils/elastic_search/elastic_search_utils.py
Adds transaction_timestamp to the Tokens API response, so the user can sort by oldest to newest tokens, or vice-versa.
Considerations:
- When passing a keyword, the date type must be passed on sort structure, e.g. `name.keyword` or `symbol.keyword`. However, when a `long` type is passed, like `transaction_timestamp` field, we should not append `.long`. This is why the data type structure was changed on this PR.
=> feat: add transaction timestamp to Tokens API response

serverless.yml
We should not send OK alerts when there are no more error logs being logged
With the upcoming integration with Opsgenie, if we keep sending OK alerts, Opsgenie will keep closing the alerts it receives.
There is no point in doing this, the on-call should close them if needed.
=> chore: do not send ok alarms for error logs

serverless.yml
[Testnet deployment](https://github.com/HathorNetwork/hathor-explorer-service/runs/6891747988?check_suite_focus=true) failed because the definition of the `get_token_balances_handler` endpoint on serverless.yml is too long.
It seems that an `_` takes 11 characters (The string `Underscore`), so I prioritized removing this character.
This PR should reduce `get_token_balances_handler` from  74 to 57 characters. 64 is the maximum allowed.
=> fix: reduce endpoint name

serverless.yml
[Deploy is failing](https://github.com/HathorNetwork/hathor-explorer-service/runs/6905130392?check_suite_focus=true) because of a typo on a `cacheKeyParameter` of  `get_tokenbalances_handler` API.
I checked and this is the only typo on `cacheKeyParameters`.
=> fix: typo on querystring of cacheKeyParameters

gateways/token_api_gateway.py, gateways/token_balances_api_gateway.py, handlers/token_api.py, serverless.yml, tests/unit/gateways/clients/test_elastic_search_client.py, tests/unit/gateways/test_token_api_gateway.py, tests/unit/gateways/test_token_balances_api_gateway.py, tests/unit/usecases/test_token_api.py, tests/unit/utils/elastic_search/test_elastic_search_utils.py, usecases/token_api.py, utils/elastic_search/elastic_search_utils.py, utils/elastic_search/transformations/token_api.py
- We should have an API to retrieve a specific token by its token_id
- We should add the `transactions_count` attribute to the token response
- We should remove the `transactions` aggregation from the token information API
=> feat: get token by token_id API and add transactions count to token return

gateways/clients/wallet_service_db_client.py, gateways/wallet_service_gateway.py, tests/unit/gateways/clients/test_wallet_service_db_client.py, tests/unit/gateways/test_wallet_service.py
Since HTR is searched before any token, both queries we make will not contain all tokens so we should query for the total number of tokens separately.
=> fix: count tokens query

gateways/token_api_gateway.py
- The token API should query only the correct index, and not all of them
=> fix: adding index to the token api query

serverless.yml
- We should update the cache parameters for the address history API so it will cache properly
=> chore: fixed cache key params on handle address history

Dockerfile_Daemons
`poetry install --no-dev` now removes its own dependencies since `--no-dev` implies a production environment.
This broke the `Dockerfile_Daemons` since the container command runs `poetry run python ...` and a missing dependency error is raised (this [alert](https://hathor.app.opsgenie.com/alert/detail/62773674-a3f5-4d59-b345-ab3cfe4e3aef-1666039181373/details))
To fix this we run the command from python instead of poetry.
- Do not use poetry commands on production after `poetry install --no-dev`.
=> fix: do not use poetry after install --no-dev

.github/workflows/pr-validation.yml, daemons/data_collector.py, gateways/node_gateway.py
- The PR checks in Github Actions should run for PRs that were just opened. They weren't before.
=> fix: the PR checks were not running for recently opened PRs

poetry.lock, pyproject.toml
- Bump python-hathorlib to v0.3.0
=> chore: upgrade dependency python-hathorlib to v0.3.0

.github/workflows/deploy.yml, serverless.yml
- The deploy pipeline should run successfully
We started to have problems with `serverless-python-requirements` plugin when deploying the Lambdas: https://github.com/HathorNetwork/hathor-explorer-service/actions/runs/3542218948/jobs/5947524789
The error was `python3.8 not found`.
Setting the python to be used by the plugin to any python3 available solves the issue (reference: https://stackoverflow.com/questions/57740310/serverless-python3-7-not-found-try-the-pythonbin-option)
The new run is working again: https://github.com/HathorNetwork/hathor-explorer-service/actions/runs/3542880636/jobs/5948842767
=> fix: python3.8 not found during deploy

poetry.lock, pyproject.toml
This reverts commit cdaf702f23bce9cb38c2a706378fd61c807d60c7.
- We should stop receiving the error `[ERROR] Runtime.ImportModuleError: Unable to import module 'handlers/block_api': /lib64/libc.so.6: version 'GLIBC_2.28' not found (required by /opt/python/cryptography/hazmat/bindings/_rust.abi3.so) ` in the `get_best_chain_height` Lambda
=> Revert "chore: bump python-hathorlib to v0.3.0"

package-lock.json, package.json, pyproject.toml
- https://github.com/HathorNetwork/hathor-explorer-service/pull/230
=> bump: v0.7.5

package-lock.json, package.json, pyproject.toml
- https://github.com/HathorNetwork/hathor-explorer-service/pull/240
=> bump: v0.7.6

gateways/node_api_gateway.py, serverless.yml, tests/unit/gateways/test_node_api_gateway.py
- turn explicit the timeout value for Node Api lambdas
- set timeout for Node Api client calls
Closes: https://github.com/HathorNetwork/hathor-explorer-service/issues/133
=> chore: set timeout for node api calls

.github/workflows/deploy.yml, .github/workflows/pr-validation.yml
- Update github actions versions due to node12 deprecation ([reference](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/))
=> chore: update old github actions

package-lock.json, package.json
Serverless creates a lambda as a custom resource to handle logs, this lambda was running with node12 that has been deprecated and AWS does not allow it anymore.
The solution for this has been made in serverless v3 but a backport to v2 has been made ([reference](https://github.com/serverless/serverless/issues/12054#issuecomment-1632634253)).
The best long term solution would require upgrading to serverless v3, but we should check the changes in the serverless file syntax and other improvements on v3 before this upgrade.
- Upgrade serverless to v2.72.4
During the sandbox deployment I found some issues:
- Python 3.11 has some issues installing aiohttp, so I had to lock the python version on 3.9 (which is configured to run on the lambda)
- I used node v16.19.1 with npm version 8.19.3 and had …
=> chore: upgrade serverless version

Makefile, package-lock.json, package.json, serverless.yml
We should be able to use the credentials acquired with the AWS SSO login when running Serverless commands
For this, we will be using the [serverless-better-credentials](https://www.serverless.com/plugins/serverless-better-credentials)  plugin, since Serverless itself [does not offer built-in support](https://github.com/serverless/serverless/issues/7567) for it yet.
Additional reference:
- https://forum.serverless.com/t/use-aws-sso-on-sls/11521
To test this, you should log yourself in AWS using `aws sso login` (an AWS account with AWS Identity Center setup is necessary for this), then run `make deploy-lambdas` in `dev` and in the `fix/aws-sso-login` branch.
The command will fail in the `dev` branch with the following error. It will work in the `fix/aws-sso-login` branch.
```
Serverless …
```
=> fix: support for AWS SSO login with Serverless

common/configuration.py, daemons/data_collector.py, tests/unit/utils/healthcheck/test_healthcheck_ping_manager.py, utils/healthcheck/healthcheck_ping_manager.py
This feature will allow sending pings every time the data collector runs to an external uptime monitor service (see https://github.com/topics/uptime-monitor and https://github.com/topics/uptime for options, some of them are able to receive these pings)
There should be a feature-flag for this that is disabled by default.
The URL to send the ping to and the interval should be configurable, besides the api-key, if needed.
=> feat: data collector health ping

gateways/clients/hathor_core_client.py, gateways/node_gateway.py, tests/unit/usecases/test_collect_nodes_statuses.py, usecases/collect_nodes_statuses.py
- We should avoid passing callbacks between functions if the same thing can be achieved without them
- We should use a default timeout and allow changing it when calling the methods of the `HathorCoreAsyncClient`
=> refactor: avoid usage of callbacks and use timeout for hathor-core client

.github/workflows/pr-validation.yml, gateways/clients/hathor_core_client.py, gateways/node_gateway.py
- Fix the error below that was caught during tests on the dev environment.
- Make sure the CI will get things like this in the future, by making it run tests for Python 3.8 as well (we had it running only for 3.9, while our runtimes use 3.8.
```
Traceback (most recent call last):
File "./daemons_runner.py", line 5, in <module>
from daemons.data_collector import DataCollector
File "/code/daemons/data_collector.py", line 8, in <module>
from usecases.collect_nodes_statuses import CollectNodesStatuses
File "/code/usecases/collect_nodes_statuses.py", line 6, in <module>
from gateways.clients.hathor_core_client import HathorCoreAsyncClient
File "/code/gateways/clients/hathor_core_client.py", line 29, in <module>
class HathorCoreAsyncClient:
File "/code/gateways/clients/hathor_core_client.py", …
```
=> fix: some type definitions don't work on Python 3.8

tests/unit/utils/wrappers/aws/test_invoke_handler.py, utils/wrappers/aws/invoke_handler.py
- We should have unit tests for the InvokeHandler class, which had 0% test coverage previously
The motivation for this is just to increase the project's test coverage
=> chore: InvokeHandler tests

poetry.lock
- The new version of python-healthchecklib fixes a bug that was affecting us. More info in https://github.com/HathorNetwork/python-healthcheck-lib/pull/2
=> fix: use latest python-healthchecklib

domain/network/network.py, domain/network/node.py, tests/fixtures/network_factory.py, tests/fixtures/node_factory.py
- Add `best_block` to the node model supporting `dag.best_block` from the status result. This is needed to calculate the sync progress for peers using sync-v2.
=> feat: support dag.best_block from node status

domain/network/network.py, tests/unit/gateways/test_node_gateway.py
- Fix by making the best_block property Optional.
Log of the error:
```txt
[ERROR] MissingValueError: missing value for field "nodes.best_block"
Traceback (most recent call last):
File "/var/task/handlers/node_data_aggregator.py", line 10, in handle
result_aggregate = aggregate_node_data.aggregate()
File "/var/task/usecases/aggregate_node_data.py", line 39, in aggregate
old_network = self.node_gateway.get_network()
File "/var/task/gateways/node_gateway.py", line 111, in get_network
return Network.from_dict(value)
File "/var/task/domain/network/network.py", line 214, in from_dict
return from_dict(
File "/opt/python/dacite/core.py", line 63, in from_dict
value = _build_value(type_=field.type, data=transformed_value, config=config)
File "/opt/python/dacite/core.py", line 90, in _build_value …
```
=> fix: legacy node data without best_block property

.github/workflows/pr-validation.yml, Dockerfile_Serverless, poetry.lock, pyproject.toml, serverless.yml
- We should use the latest version of python-hathorlib
- The Lambdas should keep working without errors with it
Previously, when trying to upgrade `python-hathorlib`, most of the Lambdas would fail with the following  error:
```
[ERROR] Runtime.ImportModuleError: Unable to import module 'handlers/block_api': /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /opt/python/cryptography/hazmat/bindings/_rust.abi3.so)
Traceback (most recent call last):
```
This was seemingly caused by the installation process of `cryptography` package, which was building its wheels in the CI-environment, but they were incompatible with the Lambda environment. (Also check https://repost.aws/knowledge-center/lambda-python-package-compatible and https://github.com/jpadilla/pyjwt/issues/800)
There is …
=> chore: upgrade python-hathorlib

package-lock.json, package.json, pyproject.toml
- https://github.com/HathorNetwork/hathor-explorer-service/pull/308
=> bump: v0.13.0

README.md
- Update deploying information.
See [README.md rendered](https://github.com/HathorNetwork/hathor-explorer-service/blob/3449fdb7be7b1a25c52f51e44d9e63007ac18f68/README.md).
=> chore: update README.md with more information for deploying process

gateways/clients/hathor_core_client.py, gateways/healthcheck_gateway.py, tests/unit/gateways/test_healthcheck_gateway.py, tests/unit/usecases/test_healthcheck.py, usecases/get_healthcheck.py
- We should use the new hathor-core's health endpoint to build our own health response. Previously, the `/version` endpoint was being used just because the health endpoint hadn't been released yet.
=> chore: use hathor-core's health endpoint

package-lock.json, package.json
- We should upgrade Serverless and its plugins to their latest versions
- The Lambda deploy should continue working
I actually only needed to upgrade the `serverless-api-gateway-caching` to get this fix: https://github.com/DianaIonita/serverless-api-gateway-caching/pull/132
We were experiencing the problem described there in our pipeline (see https://github.com/HathorNetwork/hathor-explorer-service/actions/runs/8239853205/job/22534429751)
However, we apparently had no deprecation warnings in our project, which indicated that an upgrade to Serverless v3 would work without any breaking changes, so I've decided to go for it, and to upgrade all the plugins as well.
=> chore: upgrade Serverless and its plugins

serverless.yml
The lambda deploy failed because the lambda function name after adding the prefix of the app and staging was bigger than 64 characters (`hathor-explorer-service-mainnet-node_api_nc_blueprint_information` has 65 chars).
- Function name (`node_api_nc_blueprint_information`) must have 1 less char.
=> fix: function name is bigger than 64 chars

gateways/node_api_gateway.py, handlers/node_api.py, serverless.yml, tests/unit/gateways/test_node_api_gateway.py, tests/unit/usecases/test_node_api.py, usecases/node_api.py
- Add `before` parameter to the nc history API
=> feat: add before parameter to the nc history API

gateways/clients/hathor_core_client.py, gateways/healthcheck_gateway.py, tests/unit/gateways/test_healthcheck_gateway.py
- We should expect to receive a response with Content-Type `text/html` from hathor-core's health endpoint, and make aiohttp parse it without errors.
- After https://github.com/HathorNetwork/hathor-core/pull/1110 gets released, we will be able to revert this change. I preferred to do it instead of waiting for hathor-core, because it could take too long.
=> fix: hathor-core healthcheck

common/configuration.py, handlers/node_api.py
There are networks with low quantity of transactions that remain for a long time without transactions. Because of that, the latest tx keeps being used by blocks as parent, so it list of children increases a lot. The explorer service lambda returns 502 for any response bigger than 6mb, so some transactions (https://explorer.testnet.hathor.network/transaction/00e161a6b0bee1781ea9300680913fb76fd0fac4acab527cd9626cc1514abdc9, for example) were not being loaded.
There's no reason for the UI to receive a list of 193k elements. We should paginate it, if we decide that it's important to show all of them. For now, we are truncating it and returning the latest 100 elements.
- Truncate children list in the tx detail API to return at most 100 elements.
=> feat: truncate children in tx detail API to return at most 100 elements

package-lock.json, package.json, pyproject.toml
- Bump explorer service to v0.18.2
=> chore: bump to v0.18.2

.github/workflows/deploy-reusable.yml, .github/workflows/deploy.yml, common/configuration.py, handlers/node_api.py, package-lock.json, package.json, pyproject.toml
- https://github.com/HathorNetwork/hathor-explorer-service/pull/349
- https://github.com/HathorNetwork/hathor-explorer-service/pull/348
- https://github.com/HathorNetwork/hathor-explorer-service/pull/350
=> Release v0.18.2

.github/actions/setup-python/action.yml, .github/workflows/deploy-reusable.yml, .github/workflows/deploy.yml, package-lock.json, pyproject.toml, serverless.yml
- Fix the S3 Bucket name used in ekvilibro-mainnet
- Update the package-lock.json, because it was outdated and generating errors: https://github.com/HathorNetwork/hathor-explorer-service/actions/runs/15348675099/job/43191071862
- Change the way we install poetry-export-plugin on Github-actions. It was generating an error: https://github.com/HathorNetwork/hathor-explorer-service/actions/runs/15348866004/job/43191770849
- Decrease the name of a lambda function that was exceeding the maximum length (when deployed into ekvilibro-mainnet which adds a `ekvi-main` to the name of the function)
=> fix[ci]: ekvilibro-mainnet-deploy
